# -------------------------------------------------- Sonic
[sonic]

[sonic.address]
PLATFORM = "0x4Aca671A420eEB58ecafE83700686a2AD06b20D8"
MULTISIG = "0xF564EBaC1182578398E94868bea1AbA6ba339652"

TOKEN_USDC = "0x29219dd400f2Bf60E5a23d13Be72B486D4038894"
TOKEN_STBL = "0x78a76316F66224CBaCA6e70acB24D5ee5b2Bd2c7"

LAYER_ZERO_V2_ENDPOINT = "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B"

[sonic.uint]
LAYER_ZERO_V2_ENDPOINT_ID = 30332

# -------------------------------------------------- 9745 (Plasma)
[9745]

[9745.address]
PLATFORM = "0xd4D6ad656f64E8644AFa18e7CCc9372E0Cd256f0"
MULTISIG = "0xE929438B5B53984FdBABf8562046e141e90E8099"

TOKEN_USDT0 = "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"

LAYER_ZERO_V2_ENDPOINT = "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B"

[9745.uint]
LAYER_ZERO_V2_ENDPOINT_ID = 30383

# -------------------------------------------------- Avalanche
[avalanche]

[avalanche.address]
PLATFORM = "0x72b931a12aaCDa6729b4f8f76454855CB5195941"
MULTISIG = "0x06111E02BEb85B57caebEf15F5f90Bc82D54da3A"

TOKEN_USDC = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
TOKEN_USDT = "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"

LAYER_ZERO_V2_ENDPOINT = "0x1a44076050125825900e736c501f859c50fE728c"

[avalanche.uint]
LAYER_ZERO_V2_ENDPOINT_ID = 30106
