[sonic.address]
PRICE_AGGREGATOR_OAPP_STBL = "0xAc7046e6e1e19A20A6FEfB21497D878C782a0E87"

[9745.address]
BRIDGED_PRICE_ORACLE_STBL = "0x3661cEd5Af99bb20265e12279c985dD8af5Be2B1"

[avalanche.address]
