[sonic]
PLATFORM = 0x4Aca671A420eEB58ecafE83700686a2AD06b20D8
MULTISIG = 0xF564EBaC1182578398E94868bea1AbA6ba339652

[sonic.tokens]
TOKEN_USDC=0x29219dd400f2Bf60E5a23d13Be72B486D4038894
TOKEN_STBL=0x78a76316F66224CBaCA6e70acB24D5ee5b2Bd2c7

[sonic.layerzerov2]
LAYER_ZERO_V2_ENDPOINT_ID = 30332
LAYER_ZERO_V2_ENDPOINT = 0x6F475642a6e85809B1c36Fa62763669b1b48DD5B

[plasma]
MULTISIG = 0xE929438B5B53984FdBABf8562046e141e90E8099
PLATFORM = 0xd4D6ad656f64E8644AFa18e7CCc9372E0Cd256f0

[plasma.tokens]
TOKEN_USDT0 = 0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb

[plazma.layerzerov2]
LAYER_ZERO_V2_ENDPOINT_ID = 30383
LAYER_ZERO_V2_ENDPOINT = 0x6F475642a6e85809B1c36Fa62763669b1b48DD5B

[avalanche]
MULTISIG = 0x06111E02BEb85B57caebEf15F5f90Bc82D54da3A
PLATFORM = 0x72b931a12aaCDa6729b4f8f76454855CB5195941

[avalanche.tokens]
TOKEN_USDC = 0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E
TOKEN_USDT = 0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7

[avalanche.layerzerov2]
LAYER_ZERO_V2_ENDPOINT_ID = 30106
LAYER_ZERO_V2_ENDPOINT = 0x1a44076050125825900e736c501f859c50fE728c

