[sonic.address]
xToken = "0x902215dd96a291b256a3Aef6c4Dee62d2A9B80Cb"
xStaking = "0x17a7Cf838A7C91DE47552a9f65822B547F9A6997"
PRICE_AGGREGATOR_OAPP_MAIN_TOKEN = "0x61752dB3C155f73Cc7Dda1e70d065b804Bce5e9B"

[9745.address]
BRIDGED_PRICE_ORACLE_MAIN_TOKEN = "0x1984C54B371273Ba37030e56121Cd9d18537b2D6"

[avalanche.address]
