[sonic.address]
xToken = "0x902215dd96a291b256a3Aef6c4Dee62d2A9B80Cb"
xStaking = "0x17a7Cf838A7C91DE47552a9f65822B547F9A6997"
DAO = "0x77773Cb473aD1bfE991bA299a127F64b45C17777"
PRICE_AGGREGATOR_OAPP_MAIN_TOKEN = "0x61752dB3C155f73Cc7Dda1e70d065b804Bce5e9B"
OAPP_MAIN_TOKEN = "0xD6a8b05f08834Ed2f205E3d591CD6D1A84b7C19B"

[9745.address]
BRIDGED_PRICE_ORACLE_MAIN_TOKEN = "0x1984C54B371273Ba37030e56121Cd9d18537b2D6"
OAPP_MAIN_TOKEN = "0xfdf91362B7E9330F232e500c0236a02B0DE3e492"

[avalanche.address]
