[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = "0.8.23"
gas_limit = "18446744073709551615"
optimizer-runs = 200
evm_version = "Cancun"

[profile.lite]
optimizer = false

[doc]
title = "Stability Platform Contracts"
ignore = ["./src/test/**/*.sol"]

[fmt]
int_types = "short"
ignore = ["./src/integrations/**/*.sol"]
multiline_func_header = "params_first_multi"
line_length = 120

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
real = "${REAL_RPC_URL}"
sonic = "${SONIC_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137  }
base = { key = "${BASESCAN_API_KEY}", chain = 8453  }
arbitrum = { key = "${ARBITRUMSCAN_API_KEY}", chain = 42161  }
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 1  }
sonic = { key = "${SONICSCAN_API_KEY}", chain = 146, url = "https://api.sonicscan.org/api" }
